myNextApplication:
  component: "@sls-next/serverless-component@1.19.0-alpha.35"
  inputs:
    enableS3Acceleration: false
    bucketName: cookiebot-v2-test
    runtime:
      defaultLambda: "nodejs12.x"
      apiLambda: "nodejs12.x"
      imageLambda: "nodejs12.x" 

